### ISSUE TITLE
While executing a make local run-demo , generate_indy_pool_transactions prevents creation of Indy node.

### ISSUE THREAD

**Issue by panickervinod** [brycecurtis/indy-tutorial-sandbox#3] opened 2018-02-06 08:44 UTC
Unable to spawn an indy node ,  while running make local run-demo. Any pointers to resolving this?

```

generate_indy_pool_transactions --nodes 4 --clients 5 --ips X.X.X.X,X.X.X.X,,X.X.X.X,,X.X.X.X,
/usr/local/lib/python3.5/dist-packages/zmq/asyncio/__init__.py:13: VisibleDeprecationWarning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
    Install tornado itself to use zmq with the tornado IOLoop.
    
  from zmq.eventloop import future as _future
2018-02-06 08:35:28,668 | DEBUG    | text_file_store.py   (  43) | _append_new_line_if_req | new line check for file: /root/.indy/pool_transactions_sandbox_genesis
2018-02-06 08:35:28,668 | DEBUG    | ledger.py            ( 200) | start | Starting ledger...
2018-02-06 08:35:28,668 | DEBUG    | ledger.py            (  67) | recoverTree | Recovering tree from transaction log
2018-02-06 08:35:28,670 | DEBUG    | ledger.py            (  82) | recoverTree | Recovered tree in 0.001257087000340107 seconds
2018-02-06 08:35:28,670 | DEBUG    | text_file_store.py   (  43) | _append_new_line_if_req | new line check for file: /root/.indy/domain_transactions_sandbox_genesis
2018-02-06 08:35:28,670 | DEBUG    | ledger.py            ( 200) | start | Starting ledger...
2018-02-06 08:35:28,670 | DEBUG    | ledger.py            (  67) | recoverTree | Recovering tree from transaction log
2018-02-06 08:35:28,672 | DEBUG    | ledger.py            (  82) | recoverTree | Recovered tree in 0.0015672210001866915 seconds
2018-02-06 08:35:28,673 | DEBUG    | bls.py               (  31) | from_bytes | BlsEntity::from_bytes: >>>
2018-02-06 08:35:28,673 | DEBUG    | lib.py               (  10) | do_call | do_call: >>> name: 'indy_crypto_bls_generator_from_bytes', args: 128, <cparam 'P' (0x7fb628428230)>)
2018-02-06 08:35:28,674 | DEBUG    | lib.py               (  29) | _load_cdll | _load_cdll: >>>
2018-02-06 08:35:28,674 | DEBUG    | lib.py               (  35) | _load_cdll | _load_cdll: Detected OS name: linux
2018-02-06 08:35:28,674 | DEBUG    | lib.py               (  45) | _load_cdll | _load_cdll: Resolved libindy name is: libindy_crypto.so
2018-02-06 08:35:28,675 | DEBUG    | lib.py               (  50) | _load_cdll | _load_cdll: Init Indy Crypto logger
2018-02-06 08:35:28,675 | DEBUG    | lib.py               (  53) | _load_cdll | _load_cdll: <<< res: <CDLL 'libindy_crypto.so', handle 13ed840 at 0x7fb624a81e80>

```

**Comment by brycecurtis** [comment] 2018-02-20 13:29
I'm not able to reproduce this error.  Please verify that 'make indy-base' completed without errors.

**Comment by brycecurtis** [comment] 2018-04-20 19:16
Closing as not reproducible.

**Closed as completed by brycecurtis** 2018-04-20 19:16 UTC
